### ISSUE TITLE
Error: <semantic> TypeScript Server Error (4.7.3)

### ISSUE THREAD

**Issue by zardoy** [orta/vscode-twoslash-queries#1]
It doesn't work anywhere. Hover provider works, but ts request seems to be failing, here is what I see in `Log (Extension Host)`:

```console
[2022-06-21 04:42:57.106] [exthost] [error] Error: <semantic> TypeScript Server Error (4.7.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (c:\Users\Vitaly\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167622:23)
```

I've tried different TS version.

![image](https://user-images.githubusercontent.com/46503702/174699591-a0d19f6f-f98b-490a-8622-7b64193e8a30.png)

**Comment by orta** [comment]
unsure, I'd recommend running this extension in the debugger and taking a look

**Comment by Benno-Wu** [comment]
vscode
version: 1.68.1 (system setup)
commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

https://github.com/orta/vscode-twoslash-queries/blob/56375b1413c2806861ecbeb02e628139d3d4232a/src/extension.ts#L29
this line catch the same error, don't know where to debug
