### ISSUE TITLE
Add repository url

### ISSUE THREAD

**Issue by vltansky** [orta/vscode-twoslash-queries#10]
You should add repository url to https://marketplace.visualstudio.com/items?itemName=Orta.vscode-twoslash-queries
e.g
<img width="351" alt="image" src="https://user-images.githubusercontent.com/5851280/187242028-d8e222ad-1b0b-4fab-83c3-46c7162c2b38.png">

**Comment by orta** [comment]
Thanks (and thanks @with-heart) - done
