### ISSUE TITLE
Trigger functionality using Command Palette / shortcut

### ISSUE THREAD

**Issue by gthau** [orta/vscode-twoslash-queries#19]
Thanks for you very useful extension, I love it!

One functionality I'd like to add is to be able to auto-insert the `//  ^? ` using a shortcut, that'd be more convenient than pressing `Shift+Enter` to insert a new line and typing `// <potentially many spaces> ^?`.

I submitted a PR with the implementation. Are you interested in adding this functionality?
https://github.com/orta/vscode-twoslash-queries/pull/18

**Comment by hemisu** [comment]
help for me @orta

**Comment by orta** [comment]
This is in
