### ISSUE TITLE
Improve SEO/searchability

### ISSUE THREAD

**Issue by DanKaplanSES** [orta/vscode-twoslash-queries#20]
I guess this is more of a feature request. It took me over an hour of searching to find this extension because it is difficult to Google (or duckduckgo, or find on the vscode extension marketplace). Here are some of the things I tried:

1. vs code typescript extension expand types
1. vs code typescript extension expand types in comment
1. vs code typescript extension "// ^"
1. vs code extension that shows typescript type in comment
1. vs code extension that shows type in comment
1. vs code extension that writes type in comment

Perhaps there is some way to make it easier to find this extension. Almost all of these searches brought up "Top x vs code extensions for TypeScript," and I don't recall finding this extension anywhere in the results or in those articles.

Even if you know what you are looking for by pronunciation, typing "two slash" into the extension marketplace shows this extension as the 15th result. ("twoslash" finds it as the 1st/2nd though).

**Comment by jasikpark** [comment]
++ I only found this b/c I scrolled through my installed extensions / eventually remembered the feature was called two slash

**Comment by orta** [comment]
dunno what to really offer here, happy to accept README or package.json changes with some of these ideas but I'm not certain if that helps with respect to searching in thevscode extensions marketplace

**Comment by jasikpark** [comment]
I was reading this as more general search engine SEO, since if you can find the repo you can then click through to the extension page

**Comment by DanKaplanSES** [comment]
@orta yeah it's challenging for sure, and I'm not an SEO expert. For clarification, I meant what @jasikpark said. I care more about finding it through a Google search than the vscode marketplace. This issue I've created might actually help merely by existing.

I saw that there is a twoslash website. Does it link to this extension? 

As another idea, maybe we could find YouTube tutorials that use the extension (that's how I learned of its existence) and ask if they can link to it if they only mention it in text. (This was one of the routes I took to find its name. Unfortunately, I couldn't remember the video.)

For the readme, that image is really helpful, but maybe some text-based examples could be included after it? (I have no idea of this would make a difference.)

I'm happy to pursue some of these ideas, just let me know which ones (if any) sound good.

**Comment by scarf005** [comment]
It is true that it is very hard to google this, currently my only way to search this extension is by this youtube video by Matt Pocock:

[![My favourite VSCode extension has 3k downloads by Matt Pocock](http://img.youtube.com/vi/u0adKDu--cA/0.jpg)](http://www.youtube.com/watch?v=u0adKDu--cA "My favourite VSCode extension has 3k downloads")

**Comment by orta** [comment]
I've done some changing to the name and description in the extension and README with 1.2.0, should be better now
