### ISSUE TITLE
Default Extension Keyboard Shortcut conflicts with VSCode

### ISSUE THREAD

**Issue by hanneswidrig** [orta/vscode-twoslash-queries#29]
The default shortcut for this extension uses `Ctrl+K 6` on Windows and `Cmd+K 6` on Mac. This creates issues when trying to use `Cmd+K` to clear the terminal history on a Mac or `Ctrl+K` on Windows.

I'd suggest using a different shortcut or at least detailing this possible conflict in the README.

**Comment by orta** [comment]
I think this shortcut could use the 'is in editor' context to bypass this issue, open to PRs 👍🏻

**Comment by hanneswidrig** [comment]
@orta PR has been created.

**Comment by hanneswidrig** [comment]
It's still not working correctly, I'll dig into what's wrong.
