### ISSUE TITLE
alternative name suggestion: `inlay type hint comments`

### ISSUE THREAD

**Issue by scarf005** [orta/vscode-twoslash-queries#33]
# Summary

related: #20

Renaming the extension to `inlay type hint comments` might make it easier for users to find this extension.

## Motivation

Although this extension is great, I had a hard time finding it on the marketplace (even when I've already installed it). My instinct was to search for names like:

- comment type
- type inlay hint comment
- typescript comment type hint

however it wasn't easy to find:

| comment type (19th) | type inlay hint comment (not in screen) | typescript comment type hint (not in screen) |
| :-----------------: | :---------------------------------: | :--------------------------------------: |
|  ![][comment-type]  |    ![][type-inlay-hint-comment]     |    ![][typescript-comment-type-hint]     |

[comment-type]: https://github.com/orta/vscode-twoslash-queries/assets/54838975/4bf9eec9-4095-46f3-9d66-516a108c1b4b
[type-inlay-hint-comment]: https://github.com/orta/vscode-twoslash-queries/assets/54838975/d879c17a-0260-4ac2-a951-c2e45d674ca6
[typescript-comment-type-hint]: https://github.com/orta/vscode-twoslash-queries/assets/54838975/7783e1f2-e9fc-4362-93f6-8f36ad30bade

## Rationale

There are only two extensions using the name `twoslash`, and it might not be conventional to refer to `//` comments as `twoslash` comments. Since English isn't my first language, I struggled to figure out that `twoslash` meant the same thing as `//`.

Whereas the term `inlay hint` is officially used in VS Code settings, it might be easier to search for.

![twoslash](https://github.com/orta/vscode-twoslash-queries/assets/54838975/883736eb-b44b-40cb-9325-36f67846e0b6)
![settings](https://github.com/orta/vscode-twoslash-queries/assets/54838975/7d523c61-5942-4a79-82aa-8d0723c38467)

**Comment by orta** [comment]
Twoslash is: https://shikijs.github.io/twoslash/ 

I'm not against adding those terms in the description etc, but it is the twoslash syntax in vscode and I'm not really planning on renaming it. I'd recommend focusing that energy on figuring out the right want to recommend it get inlined to vscode: https://github.com/microsoft/TypeScript/issues/52839

**Comment by scarf005** [comment]
i see. thanks for the clarification.
