### ISSUE TITLE
What is the advantage of this plugin over hover information?

### ISSUE THREAD

**Issue by ooker777** [orta/vscode-twoslash-queries#37]
You can quickly open it with <kbd>Ctrl+K Ctrl+I</kbd>:

![](https://code.visualstudio.com/assets/docs/languages/javascript/hover.png) 

I guess with this plugin the type is permanently display? But when is the case that you need that?

**Comment by orta** [comment]
Yep, or for docs.

**Comment by ooker777** [comment]
Can you elaborate the use cases that the hover info cannot do or is more inconvenient than this?

**Comment by ooker777** [comment]
It's convenient in writing code in documentation or screenshot, where a proper IDE isn't available. E.g.:
```ts
import { capitalize } from 'string-ts'

const str = 'hello world'
const result = capitalize(str)
//    ^ 'Hello world'
```
![](https://private-user-images.githubusercontent.com/566971/272358712-0aa5603f-871d-4eb7-8ace-6a73466cec4d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODk2OTYsIm5iZiI6MTcxMTA4OTM5NiwicGF0aCI6Ii81NjY5NzEvMjcyMzU4NzEyLTBhYTU2MDNmLTg3MWQtNGViNy04YWNlLTZhNzM0NjZjZWM0ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwNjM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2UzMzhkOTZlYTIwNDNlMGE1MzVmYjM4NWJhMjY0ZmI2N2VlZjUwN2NjMDU1YjMwZDkxMWFlMjViMDQ4NjZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R4HeiSBuCCFBtgoAxuRSNDdNaRu2ZdMjtnVwlcAdos0) 
(Taken from [gustavoguichard/string-ts: Strongly typed string functions](https://github.com/gustavoguichard/string-ts?tab=readme-ov-file#charat "gustavoguichard/string-ts: Strongly typed string functions"))
