### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by tonyxiao** [orta/vscode-twoslash-queries#6]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/696842/180113295-a2d65256-68e6-4f2e-91ea-0bd7cf02e721.png">

```ts

export type abc = 'asdf'
// ^?

interface Box<T> {
  value: T
}
// ^?
function makeBox<T>(value: T) {
  return {value}
}
// ^?
```
I installed and couldn't get it to work. This is what my test file looks like. What am I missing?

**Comment by orta** [comment]
the x position of the `^?` is important, it needs to be exactly the line underneath the thing you want it to look at

**Comment by yandongxu** [comment]
> <img alt="image" width="876" src="https://user-images.githubusercontent.com/696842/180113295-a2d65256-68e6-4f2e-91ea-0bd7cf02e721.png">
> 
> ```ts
> export type abc = 'asdf'
> // ^?
> 
> interface Box<T> {
>   value: T
> }
> // ^?
> function makeBox<T>(value: T) {
>   return {value}
> }
> // ^?
> ```
> 
> I installed and couldn't get it to work. This is what my test file looks like. What am I missing?

Try add 2 indents(4 spaces) before `^`
```
type abc = 'asdf';
//    ^?
```

@orta `export type` and `interface` are not working

**Comment by orta** [comment]
Give some code examples of what you think is wrong
