### ISSUE TITLE
Extension does not seem to work

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [orta/vscode-twoslash-queries#7]
I have all inlay hints options on but nothing is showing up.

Version: 1.71.0-insider
Commit: 235a92a3693176fbf9af16ec5b829c458a1d682f
Date: 2022-08-22T05:16:19.478Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: Yes

**Comment by orta** [comment]
I'd recommend cloning the repo and having a look around

**Comment by sschneider-ihre-pvs** [comment]
ok got, it, in vue it does not work because the scope is limited to this. Although the scope is shown as typescript.

![image](https://user-images.githubusercontent.com/86342787/188875280-34cf6111-d3c2-416b-92a6-57eece8d0987.png)

**Comment by orta** [comment]
See: https://github.com/orta/vscode-twoslash-queries/pull/3
