### ISSUE TITLE
Add inline option?

### ISSUE THREAD

**Issue by wesbos** [orta/vscode-twoslash-queries#8]
I love this extension, I'd love to see an option where we can inline the type right beside the variable:

```ts
pizza; // ? const pizza: Pizza
```

This is really helpful when teaching and sharing code because you can make the types visible without taking up too much room

**Comment by orta** [comment]
strictly speaking this isn't then the official twoslash format (though I guess that can be whatever I want it to be within reason)

I'd be open to  `<?` which I think gets the feel of `^?` and should be easy to have a regex for:

```ts
abc.b // <?  (property) b whatever
```

Allowing for:

```ts
abc.b // <?  (property) b whatever
//^? const abc
```


/cc @mattpocock might make a good stream, happy to pair on it sometime

**Comment by mattpocock** [comment]
I agree with this suggestion! And yeah this would be a fun stream for sure.

**Comment by NWYLZW** [comment]
Now I support this method of relative location query, and also support more functions.

[![left-right-point](https://raw.githubusercontent.com/NWYLZW/vscode-comment-queries/main/images/left-right-point.gif)](https://github.com/NWYLZW/vscode-comment-queries#%E7%9B%B8%E5%AF%B9%E6%9F%A5%E8%AF%A2)

by [vscode-comment-queries](https://github.com/NWYLZW/vscode-comment-queries)

**Comment by joeytwiddle** [comment]
Another way to approach this would be to annotate _all_ relevant lines, without needing to add any comment at all. This would then be a feature that users could toggle on/off via a palette command.

[Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) can annotate lines this way:

<img src="https://raw.githubusercontent.com/usernamehw/vscode-error-lens/master/img/demo.png">

This would of course use more CPU, but add convenience. That might be an acceptable trade-off for some users.
